### ISSUE TITLE
Diseño web - corrección

### ISSUE THREAD

**Issue by Pericena** [AndreaLaruta/cleaningService#8]
Corregir usando paint o otra herramienta , definir que se va quitar o aumentar aqui se puede definir los colores 
![Image](https://github.com/user-attachments/assets/957b0ec0-b29c-4f7b-b1ca-c20d604532a0)

**Comment by AndreaLaruta** [comment]
No me gusta que tiene estilos en el mismo html, me da ansiedad tu template

**Comment by Pericena** [comment]
Lo puedes mover si gusta al archivo css

**Comment by Pericena** [comment]
Se realizo correcciones
